# Generated by Django 4.1.1 on 2022-09-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor'},
        ),
    ]
