# Generated by Django 4.1.1 on 2022-09-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=20, verbose_name='referencia del producto'),
        ),
    ]
