# Generated by Django 4.1.1 on 2022-09-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='¿esta activo?'),
        ),
    ]
