# Generated by Django 4.1.1 on 2022-09-17 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_producto_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
